language: go

notifications:
  email: false

env:
  global:
    - PATH=$HOME/gopath/bin:$PATH

before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get golang.org/x/tools/cmd/goimports
  - go get golang.org/x/tools/cmd/vet
  - go get github.com/golang/lint/golint
  - go get github.com/mattn/goveralls

install:
  - go get ./...

before_script:
  - wget https://gist.githubusercontent.com/karlek/56595e7f313f8a74d66e/raw/goclean.sh
  - chmod +x goclean.sh

script:
  - ./goclean.sh
